// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAylOCQMmbaggeP6etrG0O2I1kwLFNGAE4',
    appId: '1:379703270845:web:0af22c670a176c1414c6d4',
    messagingSenderId: '379703270845',
    projectId: 'notes-bf85a',
    authDomain: 'notes-bf85a.firebaseapp.com',
    storageBucket: 'notes-bf85a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-ki0XLZOgX2iMoBUzpZBWrmqbBlWQoUI',
    appId: '1:379703270845:android:99118e24ba83eca814c6d4',
    messagingSenderId: '379703270845',
    projectId: 'notes-bf85a',
    storageBucket: 'notes-bf85a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrAhRuSO9gha7jEsfHoY1jYY7fJaap67I',
    appId: '1:379703270845:ios:1708944804e5901a14c6d4',
    messagingSenderId: '379703270845',
    projectId: 'notes-bf85a',
    storageBucket: 'notes-bf85a.appspot.com',
    iosClientId: '379703270845-mrh41051385k7ltq5ab0cr98f75ofden.apps.googleusercontent.com',
    iosBundleId: 'com.ars.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrAhRuSO9gha7jEsfHoY1jYY7fJaap67I',
    appId: '1:379703270845:ios:1708944804e5901a14c6d4',
    messagingSenderId: '379703270845',
    projectId: 'notes-bf85a',
    storageBucket: 'notes-bf85a.appspot.com',
    iosClientId: '379703270845-mrh41051385k7ltq5ab0cr98f75ofden.apps.googleusercontent.com',
    iosBundleId: 'com.ars.notes',
  );
}
